{% set name = "perl" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: d17aa3de50e535dd95842246f4b0d0d7713d787171c8464aa63b5c82df3a601e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - six
  run:
    - python
    - six

test:
  imports:
    - perl
  requires:
    - pytest
    - pytest-black
    - pytest-cov
    - pytest-flake8
    - pytest-isort
    - pytest-mypy

about:
  home: "http://radiac.net/projects/python-perl/"
  license: BSD
  license_family: BSD
  license_file: 
  summary: "Perl as a Python package"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
